### ISSUE TITLE
Feedback for V0.03

### ISSUE THREAD

**Issue by nirandiw** [CS2103JAN2017-T11-B2/main#137]
# Developer Guide

- Figure 2.4.1 : Structure of the Model Component is not showing. 

- Figure 2.5.3 :  There is an error hanging. 

- Figure 2.1.1 : Architecture Diagram: Are you still using the web component?

# User Guide.

- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by jjamay** [comment]
andy you were on dev guide for 0.3, can you get this fixed please if it is not fixed already?

**Comment by jjamay** [comment]
@JustinSYDE do you know what is meant by "error hanging"?

**Comment by jjamay** [comment]
- [x] Figure 2.4.1 : Structure of the Model Component is not showing.
- [x] Figure 2.5.3 : There is an error hanging.
- [x] Figure 2.1.1 : Architecture Diagram: Are you still using the web component?
- [x] The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by jjamay** [comment]
guys you can use branch devguide-fixes for this

**Comment by pengchengan** [comment]
ok I'm on it.
what's wrong with 2.5.3? The green arrow?

**Comment by jjamay** [comment]
I'm not actually sure, let's wait for @JustinSYDE to respond, he made that diagram.

**Comment by nirandiw** [comment]
Sorry guys. I meant Figure 2.5.3 : There is an arrow hanging. An arrow starts from a timeline of a class and ends in a timeline of a class.

**Comment by jjamay** [comment]
ok I think justin might need to fix this since he made the diagram in Keynote

**Comment by justinhw** [comment]
@nirandiw are you referring to the 'post(saveFilePathChangedEvent)' arrow?

I followed diagram 2.1.3b (from the original docs) which has a similar arrow indicating that a post was made 

is this incorrect?
