### ISSUE TITLE
As a user I can create recurring tasks on a daily/weekly basis, so that I don't need to create it every time.

### ISSUE THREAD

**Issue by justinhw** [CS2103JAN2017-T11-B2/main#31]

**Comment by jjamay** [comment]
#5

**Comment by pengchengan** [comment]
Add recurring task format
add s/"startTime" e/"endTime" t/"tag" r/"whichDayOfTheWeek" "endMonth/year"
StartTime and endTime should only have time info.
ex: 
add s/11:00AM e/12:00PM t/recurringEvent r/THU 04/17
This command should add four event tasks.(4/6, 4/13, /20, 4/27)

**Comment by jjamay** [comment]
should it be possible for the user to specify a startMonth/year as well?

**Comment by pengchengan** [comment]
Maybe I should ask user to specify startDay/month/year and endMonth/year
ex:
add taskname s/11:00AM e/12:00PM t/recurringEvent r/6/4/17 4/17

**Comment by pengchengan** [comment]
It's done, waiting for merging

**Comment by justinhw** [comment]
@pengchengan can we close this

**Comment by justinhw** [comment]
Not adding to v0.5 closing
