### ISSUE TITLE
As a user I can update the starttime and endtime of a todo

### ISSUE THREAD

**Issue by jjamay** [CS2103JAN2017-T11-B2/main#61]
#9

**Comment by justinhw** [comment]
Need to be able to edit a task without entering a new name

**Comment by pengchengan** [comment]
fixed it.
branch edit-issue-61

**Comment by pengchengan** [comment]
branch edit-issue-61 merged

**Comment by pengchengan** [comment]
Merge pull request #121 from CS2103JAN2017-T11-B2/add_edit_bug_fix
