### ISSUE TITLE
Fix pptx files in Docs and save them as images to be used in DeveloperGuide.md

### ISSUE THREAD

**Issue by jjamay** [CS2103JAN2017-T11-B2/main#73]
Andy, right now the images in DeveloperGuide.md have references to AddressBook. Could you please fix these files by editing the .pptx files and saving them as images? Justin and I can't do this because we are both working on Macs and can't save .pptx files.

**Comment by pengchengan** [comment]
fixed it.
Including the picture.
You can't find any address in DevGuide now.
branch edit-issue-61.

**Comment by pengchengan** [comment]
branch edit-issue-61 merged.
