### ISSUE TITLE
As a user I can add/edit a task's starttime/endtime without specifying the time

### ISSUE THREAD

**Issue by justinhw** [CS2103JAN2017-T11-B2/main#79]
default to 12:00am

**Comment by jjamay** [comment]
Should support "today" or "tomorrow"

**Comment by pengchengan** [comment]
So should we let the program know what day today is?
Currently I just set a specific datetime as a default.
It's in EditCommandparser and AddCommand.
I'll do the today or tomorrow feature in v0.5.

**Comment by justinhw** [comment]
yes the program needs to know what today is

**Comment by jjamay** [comment]
Date date = new Date() gets current time

**Comment by justinhw** [comment]
Closing as per Andy's PR

**Comment by jjamay** [comment]
default to 12:00am of the day specified

**Comment by justinhw** [comment]
overwriting tags removes s/ e/ too - this is a bug

**Comment by justinhw** [comment]
@pengchengan can we close this
