### ISSUE TITLE
Edit Command Tests have a lot of addressbook references and addressbook related stuff

### ISSUE THREAD

**Issue by jjamay** [CS2103JAN2017-T11-B2/main#84]
For example this has nothing to do with todo list:

@Test
    public void editEventToDeadLineSuccess() throws Exception {
        String detailsToEdit = "Bobbye/6:00AM 17/11/11 t/husband";
        int addressBookIndex = 9;

        TestTodo editedTodo = new TodoBuilder().withName("Bobby").
                withEndTime("6:00AM 17/11/11").withTags("husband").build();

        assertEditSuccess(addressBookIndex, addressBookIndex, detailsToEdit, editedTodo);
    }

**Comment by pengchengan** [comment]
Change all "addressBook" to "todoList"
in branch edit-issue-61

**Comment by pengchengan** [comment]
merged edit-issue-61
